(function(e){function i(a,c){var j=typeof a[c];return j==h||!!(j==b&&a[c])||"unknown"==j}function o(a,c){return!!(typeof a[c]==b&&a[c])}function w(a,c){return typeof a[c]!=f}function u(a){return function(c,j){for(var b=j.length;b--;)if(!a(c,j[b]))return!1;return!0}}function I(c){return c&&s(c,N)&&a(c,k)}function z(a){return o(a,"body")?a.body:a.getElementsByTagName("body")[0]}function x(a){o(window,"console")&&i(window.console,"log")&&window.console.log(a)}function p(a){j.initialized=!0;j.supported=
!1;a="Rangy is not supported on this page in your browser. Reason: "+a;j.config.alertOnFail?window.alert(a):x(a)}function F(){if(!j.initialized){var b,h=!1,e=!1;i(document,"createRange")&&(b=document.createRange(),s(b,m)&&a(b,l)&&(h=!0));b=z(document);if(!b||"body"!=b.nodeName.toLowerCase())p("No body element found");else if(b&&i(b,"createTextRange")&&(b=b.createTextRange(),I(b)&&(e=!0)),!h&&!e)p("Neither Range nor TextRange are available");else{j.initialized=!0;j.features={implementsDomRange:h,implementsTextRange:e};
var f,k;for(k in c)(f=c[k])instanceof D&&f.init(f,j);e=0;for(f=R.length;e<f;++e)try{R[e](j)}catch(J){h="Rangy init listener threw an exception. Continuing. Detail: "+(J.message||J.description||""+J),x(h)}}}}function D(a,c,b){this.name=a;this.dependencies=c;this.supported=this.initialized=!1;this.initializer=b}function L(a,b,h,e){a=new D(b,h,function(a){if(!a.initialized){a.initialized=!0;try{e(j,a),a.supported=!0}catch(c){x("Module '"+b+"' failed to load: "+(c.message||c.description||""+c))}}});c[b]=
a}function E(){}var B="function"==typeof e.define&&e.define.amd,b="object",h="function",f="undefined",l="startContainer startOffset endContainer endOffset collapsed commonAncestorContainer".split(" "),m="setStart setStartBefore setStartAfter setEnd setEndBefore setEndAfter collapse selectNode selectNodeContents compareBoundaryPoints deleteContents extractContents cloneContents insertNode surroundContents cloneRange toString detach".split(" "),k="boundingHeight boundingLeft boundingTop boundingWidth htmlText text".split(" "),
N="collapse compareEndPoints duplicate moveToElementText parentElement select setEndPoint getBoundingClientRect".split(" "),s=u(i),y=u(o),a=u(w),c={},j={version:"1.3alpha.20140716",initialized:!1,supported:!0,util:{isHostMethod:i,isHostObject:o,isHostProperty:w,areHostMethods:s,areHostObjects:y,areHostProperties:a,isTextRange:I,getBody:z},features:{},modules:c,config:{alertOnFail:!0,alertOnWarn:!1,preferTextRange:!1}};j.fail=p;j.warn=function(a){a="Rangy warning: "+a;j.config.alertOnWarn?window.alert(a):
x(a)};({}).hasOwnProperty?j.util.extend=function(a,c,b){var h,e,f;for(f in c)c.hasOwnProperty(f)&&(h=a[f],e=c[f],b&&(null!==h&&"object"==typeof h&&null!==e&&"object"==typeof e)&&j.util.extend(h,e,!0),a[f]=e);c.hasOwnProperty("toString")&&(a.toString=c.toString);return a}:p("hasOwnProperty not supported");(function(){var a=document.createElement("div");a.appendChild(document.createElement("span"));var c=[].slice,b;try{1==c.call(a.childNodes,0)[0].nodeType&&(b=function(a){return c.call(a,0)})}catch(e){}b||
(b=function(a){for(var c=[],b=0,j=a.length;b<j;++b)c[b]=a[b];return c});j.util.toArray=b})();var J;i(document,"addEventListener")?J=function(a,c,b){a.addEventListener(c,b,!1)}:i(document,"attachEvent")?J=function(a,c,b){a.attachEvent("on"+c,b)}:p("Document does not have required addEventListener or attachEvent method");j.util.addListener=J;var R=[];j.init=F;j.addInitListener=function(a){j.initialized?a(j):R.push(a)};var O=[];j.addCreateMissingNativeApiListener=function(a){O.push(a)};j.createMissingNativeApi=
function(a){a=a||window;F();for(var c=0,b=O.length;c<b;++c)O[c](a)};D.prototype={init:function(){for(var a=this.dependencies||[],b=0,j=a.length,e,h;b<j;++b){h=a[b];e=c[h];if(!e||!(e instanceof D))throw Error("required module '"+h+"' not found");e.init();if(!e.supported)throw Error("required module '"+h+"' not supported");}this.initializer(this)},fail:function(a){this.initialized=!0;this.supported=!1;throw Error("Module '"+this.name+"' failed to load: "+a);},warn:function(a){j.warn("Module "+this.name+
": "+a)},deprecationNotice:function(a,c){j.warn("DEPRECATED: "+a+" in module "+this.name+"is deprecated. Please use "+c+" instead")},createError:function(a){return Error("Error in Rangy "+this.name+" module: "+a)}};j.createModule=function(a){var c,b;2==arguments.length?(c=arguments[1],b=[]):(c=arguments[2],b=arguments[1]);L(!1,a,b,c)};j.createCoreModule=function(a,c,b){L(!0,a,c,b)};j.RangePrototype=E;j.rangePrototype=new E;j.selectionPrototype=new function(){};var Q=!1,y=function(){Q||(Q=!0,j.initialized||
F())};typeof window==f?p("No window found"):typeof document==f?p("No document found"):(i(document,"addEventListener")&&document.addEventListener("DOMContentLoaded",y,!1),J(window,"load",y),B&&function(a){a(function(){j.amd=!0;return j})}(e.define),e.rangy=j)})(this);
rangy.createCoreModule("DomUtil",[],function(e,i){function o(a){for(var c=0;a=a.previousSibling;)++c;return c}function w(a,c){var b=[],e;for(e=a;e;e=e.parentNode)b.push(e);for(e=c;e;e=e.parentNode)if(N(b,e))return e;return null}function u(a,c,b){for(c=b?c:c.parentNode;c;){if(c===a)return!0;c=c.parentNode}return!1}function I(a,c,b){for(b=b?a:a.parentNode;b;){a=b.parentNode;if(a===c)return b;b=a}return null}function z(a){a=a.nodeType;return 3==a||4==a||8==a}function x(a,c){var b=c.nextSibling,e=c.parentNode;
b?e.insertBefore(a,b):e.appendChild(a);return a}function p(a){if(9==a.nodeType)return a;if(typeof a.ownerDocument!=l)return a.ownerDocument;if(typeof a.document!=l)return a.document;if(a.parentNode)return p(a.parentNode);throw i.createError("getDocument: no document found for node");}function F(a){a=p(a);if(typeof a.defaultView!=l)return a.defaultView;if(typeof a.parentWindow!=l)return a.parentWindow;throw i.createError("Cannot get a window object for node");}function D(a){if(typeof a.contentDocument!=
l)return a.contentDocument;if(typeof a.contentWindow!=l)return a.contentWindow.document;throw i.createError("getIframeDocument: No Document object found for iframe element");}function L(a){return a&&m.isHostMethod(a,"setTimeout")&&m.isHostObject(a,"document")}function E(){return!1}function B(a){return!a?"[No node]":s&&E(a)?"[Broken node]":z(a)?'"'+a.data+'"':1==a.nodeType?"<"+a.nodeName+(a.id?' id="'+a.id+'"':"")+">[index:"+o(a)+",length:"+a.childNodes.length+"]["+(a.innerHTML||"[innerHTML not supported]").slice(0,
25)+"]":a.nodeName}function b(a){this._next=this.root=a}function h(a,c){this.node=a;this.offset=c}function f(a){this.code=this[a];this.codeName=a;this.message="DOMException: "+this.codeName}var l="undefined",m=e.util;m.areHostMethods(document,["createDocumentFragment","createElement","createTextNode"])||i.fail("document missing a Node creation method");m.isHostMethod(document,"getElementsByTagName")||i.fail("document missing getElementsByTagName method");var k=document.createElement("div");m.areHostMethods(k,
["insertBefore","appendChild","cloneNode"])||i.fail("Incomplete Element implementation");m.isHostProperty(k,"innerHTML")||i.fail("Element is missing innerHTML property");k=document.createTextNode("test");m.areHostMethods(k,["splitText","deleteData","insertData","appendData","cloneNode"])||i.fail("Incomplete Text Node implementation");var N=function(a,c){for(var b=a.length;b--;)if(a[b]===c)return!0;return!1},s=!1;(function(){var a=document.createElement("b");a.innerHTML="1";var c=a.firstChild;a.innerHTML=
"<br>";s=E(c);e.features.crashyTextNodes=s})();var y;typeof window.getComputedStyle!=l?y=function(a,c){return F(a).getComputedStyle(a,null)[c]}:typeof document.documentElement.currentStyle!=l?y=function(a,c){return a.currentStyle[c]}:i.fail("No means of obtaining computed style properties found");b.prototype={_current:null,hasNext:function(){return!!this._next},next:function(){var a=this._current=this._next,c;if(this._current){c=a.firstChild;if(!c)for(c=null;a!==this.root&&!(c=a.nextSibling);)a=a.parentNode;
this._next=c}return this._current},detach:function(){this._current=this._next=this.root=null}};h.prototype={equals:function(a){return!!a&&this.node===a.node&&this.offset==a.offset},inspect:function(){return"[DomPosition("+B(this.node)+":"+this.offset+")]"},toString:function(){return this.inspect()}};f.prototype={INDEX_SIZE_ERR:1,HIERARCHY_REQUEST_ERR:3,WRONG_DOCUMENT_ERR:4,NO_MODIFICATION_ALLOWED_ERR:7,NOT_FOUND_ERR:8,NOT_SUPPORTED_ERR:9,INVALID_STATE_ERR:11,INVALID_NODE_TYPE_ERR:24};f.prototype.toString=
function(){return this.message};e.dom={arrayContains:N,isHtmlNamespace:function(a){var c;return typeof a.namespaceURI==l||null===(c=a.namespaceURI)||"http://www.w3.org/1999/xhtml"==c},parentElement:function(a){a=a.parentNode;return 1==a.nodeType?a:null},getNodeIndex:o,getNodeLength:function(a){switch(a.nodeType){case 7:case 10:return 0;case 3:case 8:return a.length;default:return a.childNodes.length}},getCommonAncestor:w,isAncestorOf:u,isOrIsAncestorOf:function(a,c){return u(a,c,!0)},getClosestAncestorIn:I,
isCharacterDataNode:z,isTextOrCommentNode:function(a){if(!a)return!1;a=a.nodeType;return 3==a||8==a},insertAfter:x,splitDataNode:function(a,c,b){var e=a.cloneNode(!1);e.deleteData(0,c);a.deleteData(c,a.length-c);x(e,a);if(b)for(var h=0,f;f=b[h++];)f.node==a&&f.offset>c?(f.node=e,f.offset-=c):f.node==a.parentNode&&f.offset>o(a)&&++f.offset;return e},getDocument:p,getWindow:F,getIframeWindow:function(a){if(typeof a.contentWindow!=l)return a.contentWindow;if(typeof a.contentDocument!=l)return a.contentDocument.defaultView;
throw i.createError("getIframeWindow: No Window object found for iframe element");},getIframeDocument:D,getBody:m.getBody,isWindow:L,getContentDocument:function(a,c,b){var e;a?m.isHostProperty(a,"nodeType")?e=1==a.nodeType&&"iframe"==a.tagName.toLowerCase()?D(a):p(a):L(a)&&(e=a.document):e=document;if(!e)throw c.createError(b+"(): Parameter must be a Window object or DOM node");return e},getRootContainer:function(a){for(var c;c=a.parentNode;)a=c;return a},comparePoints:function(a,c,b,e){var h;if(a==
b)return c===e?0:c<e?-1:1;if(h=I(b,a,!0))return c<=o(h)?-1:1;if(h=I(a,b,!0))return o(h)<e?-1:1;c=w(a,b);if(!c)throw Error("comparePoints error: nodes have no common ancestor");a=a===c?c:I(a,c,!0);b=b===c?c:I(b,c,!0);if(a===b)throw i.createError("comparePoints got to case 4 and childA and childB are the same!");for(c=c.firstChild;c;){if(c===a)return-1;if(c===b)return 1;c=c.nextSibling}},isBrokenNode:E,inspectNode:B,getComputedStyleProperty:y,fragmentFromNodeChildren:function(a){for(var b=p(a).createDocumentFragment(),
e;e=a.firstChild;)b.appendChild(e);return b},createIterator:function(a){return new b(a)},DomPosition:h};e.DOMException=f});
rangy.createCoreModule("DomRange",["DomUtil"],function(e){function i(a,d){return 3!=a.nodeType&&(n(a,d.startContainer)||n(a,d.endContainer))}function o(a){return a.document||P(a.startContainer)}function w(a){return new G(a.parentNode,S(a))}function u(a){return new G(a.parentNode,S(a)+1)}function I(a,d,b){var g=11==a.nodeType?a.firstChild:a;t(d)?b==d.length?r.insertAfter(a,d):d.parentNode.insertBefore(a,0==b?d:Z(d,b)):b>=d.childNodes.length?d.appendChild(a):d.insertBefore(a,d.childNodes[b]);return g}
function z(d,b,g){a(d);a(b);if(o(b)!=o(d))throw new A("WRONG_DOCUMENT_ERR");var c=C(d.startContainer,d.startOffset,b.endContainer,b.endOffset),d=C(d.endContainer,d.endOffset,b.startContainer,b.startOffset);return g?0>=c&&0<=d:0>c&&0<d}function x(a){for(var d,b,g=o(a.range).createDocumentFragment();b=a.next();){d=a.isPartiallySelectedSubtree();b=b.cloneNode(!d);d&&(d=a.getSubtreeIterator(),b.appendChild(x(d)),d.detach());if(10==b.nodeType)throw new A("HIERARCHY_REQUEST_ERR");g.appendChild(b)}return g}
function p(a,d,b){for(var g,c,b=b||{stop:!1};g=a.next();)if(a.isPartiallySelectedSubtree())if(!1===d(g)){b.stop=!0;break}else{if(g=a.getSubtreeIterator(),p(g,d,b),g.detach(),b.stop)break}else for(g=r.createIterator(g);c=g.next();)if(!1===d(c)){b.stop=!0;return}}function F(a){for(var d;a.next();)a.isPartiallySelectedSubtree()?(d=a.getSubtreeIterator(),F(d),d.detach()):a.remove()}function D(a){for(var d,b=o(a.range).createDocumentFragment(),g;d=a.next();){a.isPartiallySelectedSubtree()?(d=d.cloneNode(!1),
g=a.getSubtreeIterator(),d.appendChild(D(g)),g.detach()):a.remove();if(10==d.nodeType)throw new A("HIERARCHY_REQUEST_ERR");b.appendChild(d)}return b}function L(a,d,b){var g=!(!d||!d.length),c,e=!!b;g&&(c=RegExp("^("+d.join("|")+")$"));var q=[];p(new B(a,!1),function(d){if(!g||c.test(d.nodeType))if(!e||b(d)){var Y=a.startContainer;d==Y&&t(Y)&&a.startOffset==Y.length||(Y=a.endContainer,d==Y&&t(Y)&&0==a.endOffset||q.push(d))}});return q}function E(a){return"["+("undefined"==typeof a.getName?"Range":
a.getName())+"("+r.inspectNode(a.startContainer)+":"+a.startOffset+", "+r.inspectNode(a.endContainer)+":"+a.endOffset+")]"}function B(a,d){this.range=a;this.clonePartiallySelectedTextNodes=d;if(!a.collapsed){this.sc=a.startContainer;this.so=a.startOffset;this.ec=a.endContainer;this.eo=a.endOffset;var b=a.commonAncestorContainer;this.sc===this.ec&&t(this.sc)?(this.isSingleCharacterDataNode=!0,this._first=this._last=this._next=this.sc):(this._first=this._next=this.sc===b&&!t(this.sc)?this.sc.childNodes[this.so]:
X(this.sc,b,!0),this._last=this.ec===b&&!t(this.ec)?this.ec.childNodes[this.eo-1]:X(this.ec,b,!0))}}function b(a){return function(d,b){for(var g,c=b?d:d.parentNode;c;){g=c.nodeType;if(U(a,g))return c;c=c.parentNode}return null}}function h(a,d){if(g(a,d))throw new A("INVALID_NODE_TYPE_ERR");}function f(a,d){if(!U(d,a.nodeType))throw new A("INVALID_NODE_TYPE_ERR");}function l(a,d){if(0>d||d>(t(a)?a.length:a.childNodes.length))throw new A("INDEX_SIZE_ERR");}function m(a,d){if(T(a,!0)!==T(d,!0))throw new A("WRONG_DOCUMENT_ERR");
}function k(a){if(d(a,!0))throw new A("NO_MODIFICATION_ALLOWED_ERR");}function N(a,d){if(!a)throw new A(d);}function s(a){return $&&r.isBrokenNode(a)||!U(aa,a.nodeType)&&!T(a,!0)}function y(a){return!!a.startContainer&&!!a.endContainer&&!s(a.startContainer)&&!s(a.endContainer)&&a.startOffset<=(t(a.startContainer)?a.startContainer.length:a.startContainer.childNodes.length)&&a.endOffset<=(t(a.endContainer)?a.endContainer.length:a.endContainer.childNodes.length)}function a(a){if(!y(a))throw Error("Range error: Range is no longer valid after DOM mutation ("+
a.inspect()+")");}function c(d,b){a(d);var g=d.startContainer,c=d.startOffset,e=d.endContainer,q=d.endOffset,h=g===e;t(e)&&(0<q&&q<e.length)&&Z(e,q,b);t(g)&&(0<c&&c<g.length)&&(g=Z(g,c,b),h?(q-=c,e=g):e==g.parentNode&&q>=S(g)&&q++,c=0);d.setStartAndEnd(g,c,e,q)}function j(a){a.START_TO_START=fa;a.START_TO_END=ia;a.END_TO_END=na;a.END_TO_START=ja;a.NODE_BEFORE=ka;a.NODE_AFTER=la;a.NODE_BEFORE_AND_AFTER=ma;a.NODE_INSIDE=ga}function J(a){j(a);j(a.prototype)}function R(d,b){return function(){a(this);
var g=this.startContainer,c=this.startOffset,e=this.commonAncestorContainer,q=new B(this,!0);g!==e&&(g=X(g,e,!0),c=u(g),g=c.node,c=c.offset);p(q,k);q.reset();e=d(q);q.detach();b(this,g,c,g,c);return e}}function O(d,b){function g(a,d){return function(b){f(b,V);f(M(b),aa);b=(a?w:u)(b);(d?q:j)(this,b.node,b.offset)}}function q(a,d,g){var c=a.endContainer,v=a.endOffset;if(d!==a.startContainer||g!==a.startOffset){if(M(d)!=M(c)||1==C(d,g,c,v))c=d,v=g;b(a,d,g,c,v)}}function j(a,d,g){var c=a.startContainer,
v=a.startOffset;if(d!==a.endContainer||g!==a.endOffset){if(M(d)!=M(c)||-1==C(d,g,c,v))c=d,v=g;b(a,c,v,d,g)}}var da=function(){};da.prototype=e.rangePrototype;d.prototype=new da;W.extend(d.prototype,{setStart:function(a,d){h(a,!0);l(a,d);q(this,a,d)},setEnd:function(a,d){h(a,!0);l(a,d);j(this,a,d)},setStartAndEnd:function(){var a=arguments,d=a[0],g=a[1],c=d,v=g;switch(a.length){case 3:v=a[2];break;case 4:c=a[2],v=a[3]}b(this,d,g,c,v)},setBoundary:function(a,d,b){this["set"+(b?"Start":"End")](a,d)},
setStartBefore:g(!0,!0),setStartAfter:g(!1,!0),setEndBefore:g(!0,!1),setEndAfter:g(!1,!1),collapse:function(d){a(this);d?b(this,this.startContainer,this.startOffset,this.startContainer,this.startOffset):b(this,this.endContainer,this.endOffset,this.endContainer,this.endOffset)},selectNodeContents:function(a){h(a,!0);b(this,a,0,a,ba(a))},selectNode:function(a){h(a,!1);f(a,V);var d=w(a),a=u(a);b(this,d.node,d.offset,a.node,a.offset)},extractContents:R(D,b),deleteContents:R(F,b),canSurroundContents:function(){a(this);
k(this.startContainer);k(this.endContainer);var d=new B(this,!0),b=d._first&&i(d._first,this)||d._last&&i(d._last,this);d.detach();return!b},splitBoundaries:function(){c(this)},splitBoundariesPreservingPositions:function(a){c(this,a)},normalizeBoundaries:function(){a(this);var d=this.startContainer,g=this.startOffset,c=this.endContainer,v=this.endOffset,e=function(a){var d=a.nextSibling;d&&d.nodeType==a.nodeType&&(c=a,v=a.length,a.appendData(d.data),d.parentNode.removeChild(d))},q=function(a){var b=
a.previousSibling;if(b&&b.nodeType==a.nodeType){d=a;var e=a.length;g=b.length;a.insertData(0,b.data);b.parentNode.removeChild(b);d==c?(v+=g,c=d):c==a.parentNode&&(b=S(a),v==b?(c=a,v=e):v>b&&v--)}},h=!0;t(c)?c.length==v&&e(c):(0<v&&(h=c.childNodes[v-1])&&t(h)&&e(h),h=!this.collapsed);h?t(d)?0==g&&q(d):g<d.childNodes.length&&(e=d.childNodes[g])&&t(e)&&q(e):(d=c,g=v);b(this,d,g,c,v)},collapseToPoint:function(a,d){h(a,!0);l(a,d);this.setStartAndEnd(a,d)}});J(d)}function Q(a){a.collapsed=a.startContainer===
a.endContainer&&a.startOffset===a.endOffset;a.commonAncestorContainer=a.collapsed?a.startContainer:r.getCommonAncestor(a.startContainer,a.endContainer)}function K(a,d,b,g,c){a.startContainer=d;a.startOffset=b;a.endContainer=g;a.endOffset=c;a.document=r.getDocument(d);Q(a)}function H(a){this.startContainer=a;this.startOffset=0;this.endContainer=a;this.endOffset=0;this.document=a;Q(this)}var r=e.dom,W=e.util,G=r.DomPosition,A=e.DOMException,t=r.isCharacterDataNode,S=r.getNodeIndex,n=r.isOrIsAncestorOf,
P=r.getDocument,C=r.comparePoints,Z=r.splitDataNode,X=r.getClosestAncestorIn,ba=r.getNodeLength,U=r.arrayContains,M=r.getRootContainer,$=e.features.crashyTextNodes;B.prototype={_current:null,_next:null,_first:null,_last:null,isSingleCharacterDataNode:!1,reset:function(){this._current=null;this._next=this._first},hasNext:function(){return!!this._next},next:function(){var a=this._current=this._next;a&&(this._next=a!==this._last?a.nextSibling:null,t(a)&&this.clonePartiallySelectedTextNodes&&(a===this.ec&&
(a=a.cloneNode(!0)).deleteData(this.eo,a.length-this.eo),this._current===this.sc&&(a=a.cloneNode(!0)).deleteData(0,this.so)));return a},remove:function(){var a=this._current,d,b;t(a)&&(a===this.sc||a===this.ec)?(d=a===this.sc?this.so:0,b=a===this.ec?this.eo:a.length,d!=b&&a.deleteData(d,b-d)):a.parentNode&&a.parentNode.removeChild(a)},isPartiallySelectedSubtree:function(){return i(this._current,this.range)},getSubtreeIterator:function(){var a;if(this.isSingleCharacterDataNode)a=this.range.cloneRange(),
a.collapse(!1);else{a=new H(o(this.range));var d=this._current,b=d,g=0,c=d,e=ba(d);n(d,this.sc)&&(b=this.sc,g=this.so);n(d,this.ec)&&(c=this.ec,e=this.eo);K(a,b,g,c,e)}return new B(a,this.clonePartiallySelectedTextNodes)},detach:function(){this.range=this._current=this._next=this._first=this._last=this.sc=this.so=this.ec=this.eo=null}};var V=[1,3,4,5,7,8,10],aa=[2,9,11],ca=[1,3,4,5,7,8,10,11],ea=[1,3,4,5,7,8],T=b([9,11]),d=b([5,6,10,12]),g=b([6,10,12]),q=document.createElement("style"),da=!1;try{q.innerHTML=
"<b>x</b>",da=3==q.firstChild.nodeType}catch(oa){}e.features.htmlParsingConforms=da;var ha="startContainer startOffset endContainer endOffset collapsed commonAncestorContainer".split(" "),fa=0,ia=1,na=2,ja=3,ka=0,la=1,ma=2,ga=3;W.extend(e.rangePrototype,{compareBoundaryPoints:function(d,b){a(this);m(this.startContainer,b.startContainer);var g=d==ja||d==fa?"start":"end",c=d==ia||d==fa?"start":"end";return C(this[g+"Container"],this[g+"Offset"],b[c+"Container"],b[c+"Offset"])},insertNode:function(d){a(this);
f(d,ca);k(this.startContainer);if(n(d,this.startContainer))throw new A("HIERARCHY_REQUEST_ERR");this.setStartBefore(I(d,this.startContainer,this.startOffset))},cloneContents:function(){a(this);var d,b;if(this.collapsed)return o(this).createDocumentFragment();if(this.startContainer===this.endContainer&&t(this.startContainer))return d=this.startContainer.cloneNode(!0),d.data=d.data.slice(this.startOffset,this.endOffset),b=o(this).createDocumentFragment(),b.appendChild(d),b;b=new B(this,!0);d=x(b);b.detach();
return d},canSurroundContents:function(){a(this);k(this.startContainer);k(this.endContainer);var d=new B(this,!0),b=d._first&&i(d._first,this)||d._last&&i(d._last,this);d.detach();return!b},surroundContents:function(a){f(a,ea);if(!this.canSurroundContents())throw new A("INVALID_STATE_ERR");var d=this.extractContents();if(a.hasChildNodes())for(;a.lastChild;)a.removeChild(a.lastChild);I(a,this.startContainer,this.startOffset);a.appendChild(d);this.selectNode(a)},cloneRange:function(){a(this);for(var d=
new H(o(this)),b=ha.length,g;b--;)g=ha[b],d[g]=this[g];return d},toString:function(){a(this);var d=this.startContainer;if(d===this.endContainer&&t(d))return 3==d.nodeType||4==d.nodeType?d.data.slice(this.startOffset,this.endOffset):"";var b=[],d=new B(this,!0);p(d,function(a){(3==a.nodeType||4==a.nodeType)&&b.push(a.data)});d.detach();return b.join("")},compareNode:function(d){a(this);var b=d.parentNode,g=S(d);if(!b)throw new A("NOT_FOUND_ERR");d=this.comparePoint(b,g);b=this.comparePoint(b,g+1);
return 0>d?0<b?ma:ka:0<b?la:ga},comparePoint:function(d,b){a(this);N(d,"HIERARCHY_REQUEST_ERR");m(d,this.startContainer);return 0>C(d,b,this.startContainer,this.startOffset)?-1:0<C(d,b,this.endContainer,this.endOffset)?1:0},createContextualFragment:da?function(a){var d=this.startContainer,b=P(d);if(!d)throw new A("INVALID_STATE_ERR");var g=null;1==d.nodeType?g=d:t(d)&&(g=r.parentElement(d));g=null===g||"HTML"==g.nodeName&&r.isHtmlNamespace(P(g).documentElement)&&r.isHtmlNamespace(g)?b.createElement("body"):
g.cloneNode(!1);g.innerHTML=a;return r.fragmentFromNodeChildren(g)}:function(a){var d=o(this).createElement("body");d.innerHTML=a;return r.fragmentFromNodeChildren(d)},toHtml:function(){a(this);var d=this.commonAncestorContainer.parentNode.cloneNode(!1);d.appendChild(this.cloneContents());return d.innerHTML},intersectsNode:function(d,b){a(this);N(d,"NOT_FOUND_ERR");if(P(d)!==o(this))return!1;var g=d.parentNode,c=S(d);N(g,"NOT_FOUND_ERR");var e=C(g,c,this.endContainer,this.endOffset),g=C(g,c+1,this.startContainer,
this.startOffset);return b?0>=e&&0<=g:0>e&&0<g},isPointInRange:function(d,b){a(this);N(d,"HIERARCHY_REQUEST_ERR");m(d,this.startContainer);return 0<=C(d,b,this.startContainer,this.startOffset)&&0>=C(d,b,this.endContainer,this.endOffset)},intersectsRange:function(a){return z(this,a,!1)},intersectsOrTouchesRange:function(a){return z(this,a,!0)},intersection:function(a){if(this.intersectsRange(a)){var d=C(this.startContainer,this.startOffset,a.startContainer,a.startOffset),b=C(this.endContainer,this.endOffset,
a.endContainer,a.endOffset),g=this.cloneRange();-1==d&&g.setStart(a.startContainer,a.startOffset);1==b&&g.setEnd(a.endContainer,a.endOffset);return g}return null},union:function(a){if(this.intersectsOrTouchesRange(a)){var d=this.cloneRange();-1==C(a.startContainer,a.startOffset,this.startContainer,this.startOffset)&&d.setStart(a.startContainer,a.startOffset);1==C(a.endContainer,a.endOffset,this.endContainer,this.endOffset)&&d.setEnd(a.endContainer,a.endOffset);return d}throw new A("Ranges do not intersect");
},containsNode:function(a,d){return d?this.intersectsNode(a,!1):this.compareNode(a)==ga},containsNodeContents:function(a){return 0<=this.comparePoint(a,0)&&0>=this.comparePoint(a,ba(a))},containsRange:function(a){var d=this.intersection(a);return null!==d&&a.equals(d)},containsNodeText:function(a){var d=this.cloneRange();d.selectNode(a);var b=d.getNodes([3]);return 0<b.length?(d.setStart(b[0],0),a=b.pop(),d.setEnd(a,a.length),this.containsRange(d)):this.containsNodeContents(a)},getNodes:function(d,
b){a(this);return L(this,d,b)},getDocument:function(){return o(this)},collapseBefore:function(a){this.setEndBefore(a);this.collapse(!1)},collapseAfter:function(a){this.setStartAfter(a);this.collapse(!0)},getBookmark:function(a){var d=o(this),b=e.createRange(d),a=a||r.getBody(d);b.selectNodeContents(a);var d=this.intersection(b),g=0,c=0;d&&(b.setEnd(d.startContainer,d.startOffset),g=b.toString().length,c=g+d.toString().length);return{start:g,end:c,containerNode:a}},moveToBookmark:function(a){var d=
a.containerNode,b=0;this.setStart(d,0);this.collapse(!0);for(var d=[d],g,c=!1,e=!1,q,h;!e&&(g=d.pop());)if(3==g.nodeType)q=b+g.length,!c&&(a.start>=b&&a.start<=q)&&(this.setStart(g,a.start-b),c=!0),c&&(a.end>=b&&a.end<=q)&&(this.setEnd(g,a.end-b),e=!0),b=q;else{h=g.childNodes;for(q=h.length;q--;)d.push(h[q])}},getName:function(){return"DomRange"},equals:function(a){return H.rangesEqual(this,a)},isValid:function(){return y(this)},inspect:function(){return E(this)},detach:function(){}});O(H,K);W.extend(H,
{rangeProperties:ha,RangeIterator:B,copyComparisonConstants:J,createPrototypeRange:O,inspect:E,getRangeDocument:o,rangesEqual:function(a,d){return a.startContainer===d.startContainer&&a.startOffset===d.startOffset&&a.endContainer===d.endContainer&&a.endOffset===d.endOffset}});e.DomRange=H});
rangy.createCoreModule("WrappedRange",["DomRange"],function(e,i){var o,w,u=e.dom,I=e.util,z=u.DomPosition,x=e.DomRange,p=u.getBody,F=u.getContentDocument,D=u.isCharacterDataNode;e.features.implementsDomRange&&function(){function b(a){for(var b=f.length,e;b--;)e=f[b],a[e]=a.nativeRange[e];a.collapsed=a.startContainer===a.endContainer&&a.startOffset===a.endOffset}var h,f=x.rangeProperties,l;o=function(a){if(!a)throw i.createError("WrappedRange: Range must be specified");this.nativeRange=a;b(this)};
x.createPrototypeRange(o,function(a,b,e,h,f){var l=a.startContainer!==b||a.startOffset!=e,k=a.endContainer!==h||a.endOffset!=f,m=!a.equals(a.nativeRange);if(l||k||m)a.setEnd(h,f),a.setStart(b,e)});h=o.prototype;h.selectNode=function(a){this.nativeRange.selectNode(a);b(this)};h.cloneContents=function(){return this.nativeRange.cloneContents()};h.surroundContents=function(a){this.nativeRange.surroundContents(a);b(this)};h.collapse=function(a){this.nativeRange.collapse(a);b(this)};h.cloneRange=function(){return new o(this.nativeRange.cloneRange())};
h.refresh=function(){b(this)};h.toString=function(){return this.nativeRange.toString()};var m=document.createTextNode("test");p(document).appendChild(m);var k=document.createRange();k.setStart(m,0);k.setEnd(m,0);try{k.setStart(m,1),h.setStart=function(a,c){this.nativeRange.setStart(a,c);b(this)},h.setEnd=function(a,c){this.nativeRange.setEnd(a,c);b(this)},l=function(a){return function(c){this.nativeRange[a](c);b(this)}}}catch(N){h.setStart=function(a,c){try{this.nativeRange.setStart(a,c)}catch(e){this.nativeRange.setEnd(a,
c),this.nativeRange.setStart(a,c)}b(this)},h.setEnd=function(a,c){try{this.nativeRange.setEnd(a,c)}catch(e){this.nativeRange.setStart(a,c),this.nativeRange.setEnd(a,c)}b(this)},l=function(a,c){return function(e){try{this.nativeRange[a](e)}catch(h){this.nativeRange[c](e),this.nativeRange[a](e)}b(this)}}}h.setStartBefore=l("setStartBefore","setEndBefore");h.setStartAfter=l("setStartAfter","setEndAfter");h.setEndBefore=l("setEndBefore","setStartBefore");h.setEndAfter=l("setEndAfter","setStartAfter");
h.selectNodeContents=function(a){this.setStartAndEnd(a,0,u.getNodeLength(a))};k.selectNodeContents(m);k.setEnd(m,3);l=document.createRange();l.selectNodeContents(m);l.setEnd(m,4);l.setStart(m,2);h.compareBoundaryPoints=-1==k.compareBoundaryPoints(k.START_TO_END,l)&&1==k.compareBoundaryPoints(k.END_TO_START,l)?function(a,b){b=b.nativeRange||b;a==b.START_TO_END?a=b.END_TO_START:a==b.END_TO_START&&(a=b.START_TO_END);return this.nativeRange.compareBoundaryPoints(a,b)}:function(a,b){return this.nativeRange.compareBoundaryPoints(a,
b.nativeRange||b)};l=document.createElement("div");l.innerHTML="123";var s=l.firstChild,y=p(document);y.appendChild(l);k.setStart(s,1);k.setEnd(s,2);k.deleteContents();"13"==s.data&&(h.deleteContents=function(){this.nativeRange.deleteContents();b(this)},h.extractContents=function(){var a=this.nativeRange.extractContents();b(this);return a});y.removeChild(l);y=null;I.isHostMethod(k,"createContextualFragment")&&(h.createContextualFragment=function(a){return this.nativeRange.createContextualFragment(a)});
p(document).removeChild(m);h.getName=function(){return"WrappedRange"};e.WrappedRange=o;e.createNativeRange=function(a){a=F(a,i,"createNativeRange");return a.createRange()}}();if(e.features.implementsTextRange){var L=function(b,e,f,l,m){var k=b.duplicate();k.collapse(f);var i=k.parentElement();u.isOrIsAncestorOf(e,i)||(i=e);if(!i.canHaveHTML)return i=new z(i.parentNode,u.getNodeIndex(i)),{boundaryPosition:i,nodeInfo:{nodeIndex:i.offset,containerElement:i.node}};e=u.getDocument(i).createElement("span");
e.parentNode&&e.parentNode.removeChild(e);for(var o,p=f?"StartToStart":"StartToEnd",a=m&&m.containerElement==i?m.nodeIndex:0,c=i.childNodes.length,j=c,m=j;;){m==c?i.appendChild(e):i.insertBefore(e,i.childNodes[m]);k.moveToElementText(e);o=k.compareEndPoints(p,b);if(0==o||a==j)break;else if(-1==o)if(j==a+1)break;else a=m;else j=j==a+1?a:m;m=Math.floor((a+j)/2);i.removeChild(e)}p=e.nextSibling;if(-1==o&&p&&D(p)){k.setEndPoint(f?"EndToStart":"EndToEnd",b);if(/[\r\n]/.test(p.data)){f=k.duplicate();l=
f.text.replace(/\r\n/g,"\r").length;for(l=f.moveStart("character",l);-1==f.compareEndPoints("StartToEnd",f);)l++,f.moveStart("character",1)}else l=k.text.length;f=new z(p,l)}else b=(l||!f)&&e.previousSibling,f=(f=(l||f)&&e.nextSibling)&&D(f)?new z(f,0):b&&D(b)?new z(b,b.data.length):new z(i,u.getNodeIndex(e));e.parentNode.removeChild(e);return{boundaryPosition:f,nodeInfo:{nodeIndex:m,containerElement:i}}},E=function(b,e){var f,i,m=b.offset,k=u.getDocument(b.node),o=p(k).createTextRange(),s=D(b.node);
s?(f=b.node,i=f.parentNode):(f=b.node.childNodes,f=m<f.length?f[m]:null,i=b.node);k=k.createElement("span");k.innerHTML="&#feff;";f?i.insertBefore(k,f):i.appendChild(k);o.moveToElementText(k);o.collapse(!e);i.removeChild(k);if(s)o[e?"moveStart":"moveEnd"]("character",m);return o};w=function(b){this.textRange=b;this.refresh()};w.prototype=new x(document);w.prototype.refresh=function(){var b,e,f;f=this.textRange;b=f.parentElement();var i=f.duplicate();i.collapse(!0);e=i.parentElement();i=f.duplicate();
i.collapse(!1);f=i.parentElement();e=e==f?e:u.getCommonAncestor(e,f);f=e==b?e:u.getCommonAncestor(b,e);0==this.textRange.compareEndPoints("StartToEnd",this.textRange)?e=b=L(this.textRange,f,!0,!0).boundaryPosition:(e=L(this.textRange,f,!0,!1),b=e.boundaryPosition,e=L(this.textRange,f,!1,!1,e.nodeInfo).boundaryPosition);this.setStart(b.node,b.offset);this.setEnd(e.node,e.offset)};w.prototype.getName=function(){return"WrappedTextRange"};x.copyComparisonConstants(w);w.rangeToTextRange=function(b){if(b.collapsed)return E(new z(b.startContainer,
b.startOffset),!0);var e=E(new z(b.startContainer,b.startOffset),!0),f=E(new z(b.endContainer,b.endOffset),!1),b=p(x.getRangeDocument(b)).createTextRange();b.setEndPoint("StartToStart",e);b.setEndPoint("EndToEnd",f);return b};e.WrappedTextRange=w;if(!e.features.implementsDomRange||e.config.preferTextRange){var B=function(){return this}();"undefined"==typeof B.Range&&(B.Range=w);e.createNativeRange=function(b){b=F(b,i,"createNativeRange");return p(b).createTextRange()};e.WrappedRange=w}}e.createRange=
function(b){b=F(b,i,"createRange");return new e.WrappedRange(e.createNativeRange(b))};e.createRangyRange=function(b){b=F(b,i,"createRangyRange");return new x(b)};e.createIframeRange=function(b){i.deprecationNotice("createIframeRange()","createRange(iframeEl)");return e.createRange(b)};e.createIframeRangyRange=function(b){i.deprecationNotice("createIframeRangyRange()","createRangyRange(iframeEl)");return e.createRangyRange(b)};e.addCreateMissingNativeApiListener(function(b){var h=b.document;"undefined"==
typeof h.createRange&&(h.createRange=function(){return e.createRange(h)});h=b=null})});
rangy.createCoreModule("WrappedSelection",["DomRange","WrappedRange"],function(e,i){function o(a){return"string"==typeof a?/^backward(s)?$/i.test(a):!!a}function w(a,g){if(a){if(s.isWindow(a))return a;if(a instanceof b)return a.win;var c=s.getContentDocument(a,i,g);return s.getWindow(c)}return window}function u(a){return w(a,"getWinSelection").getSelection()}function I(a){return w(a,"getDocSelection").document.selection}function z(a){var b=!1;a.anchorNode&&(b=1==s.comparePoints(a.anchorNode,a.anchorOffset,
a.focusNode,a.focusOffset));return b}function x(a,b,c){var e=c?"end":"start",c=c?"start":"end";a.anchorNode=b[e+"Container"];a.anchorOffset=b[e+"Offset"];a.focusNode=b[c+"Container"];a.focusOffset=b[c+"Offset"]}function p(a){a.anchorNode=a.focusNode=null;a.anchorOffset=a.focusOffset=0;a.rangeCount=0;a.isCollapsed=!0;a._ranges.length=0}function F(a){var b;a instanceof c?(b=e.createNativeRange(a.getDocument()),b.setEnd(a.endContainer,a.endOffset),b.setStart(a.startContainer,a.startOffset)):a instanceof
j?b=a.nativeRange:K.implementsDomRange&&a instanceof s.getWindow(a.startContainer).Range&&(b=a);return b}function D(a){var b=a.getNodes(),c;a:if(!b.length||1!=b[0].nodeType)c=!1;else{c=1;for(var e=b.length;c<e;++c)if(!s.isAncestorOf(b[0],b[c])){c=!1;break a}c=!0}if(!c)throw i.createError("getSingleElementFromRange: range "+a.inspect()+" did not consist of a single element");return b[0]}function L(a,b){var c=new j(b);a._ranges=[c];x(a,c,!1);a.rangeCount=1;a.isCollapsed=c.collapsed}function E(a){a._ranges.length=
0;if("None"==a.docSelection.type)p(a);else{var b=a.docSelection.createRange();if(b&&"undefined"!=typeof b.text)L(a,b);else{a.rangeCount=b.length;for(var c,f=H(b.item(0)),h=0;h<a.rangeCount;++h)c=e.createRange(f),c.selectNode(b.item(h)),a._ranges.push(c);a.isCollapsed=1==a.rangeCount&&a._ranges[0].collapsed;x(a,a._ranges[a.rangeCount-1],!1)}}}function B(a,b){for(var c=a.docSelection.createRange(),e=D(b),f=H(c.item(0)),f=r(f).createControlRange(),h=0,j=c.length;h<j;++h)f.add(c.item(h));try{f.add(e)}catch(k){throw i.createError("addRange(): Element within the specified Range could not be added to control selection (does it have layout?)");
}f.select();E(a)}function b(a,b,c){this.nativeSelection=a;this.docSelection=b;this._ranges=[];this.win=c;this.refresh()}function h(a){a.win=a.anchorNode=a.focusNode=a._ranges=null;a.rangeCount=a.anchorOffset=a.focusOffset=0;a.detached=!0}function f(a,b){for(var c=V.length,e,f;c--;)if(e=V[c],f=e.selection,"deleteAll"==b)h(f);else if(e.win==a)return"delete"==b?(V.splice(c,1),!0):f;"deleteAll"==b&&(V.length=0);return null}function l(a,b){for(var c=H(b[0].startContainer),c=r(c).createControlRange(),e=
0,f,h=b.length;e<h;++e){f=D(b[e]);try{c.add(f)}catch(j){throw i.createError("setRanges(): Element within one of the specified Ranges could not be added to control selection (does it have layout?)");}}c.select();E(a)}function m(a,b){if(a.win.document!=H(b))throw new J("WRONG_DOCUMENT_ERR");}function k(a){return function(b,c){var f;this.rangeCount?(f=this.getRangeAt(0),f["set"+(a?"Start":"End")](b,c)):(f=e.createRange(this.win.document),f.setStartAndEnd(b,c));this.setSingleRange(f,this.isBackward())}}
function N(a){var b=[],e=new R(a.anchorNode,a.anchorOffset),f=new R(a.focusNode,a.focusOffset),h="function"==typeof a.getName?a.getName():"Selection";if("undefined"!=typeof a.rangeCount)for(var i=0,j=a.rangeCount;i<j;++i)b[i]=c.inspect(a.getRangeAt(i));return"["+h+"(Ranges: "+b.join(", ")+")(anchor: "+e.inspect()+", focus: "+f.inspect()+"]"}e.config.checkSelectionRanges=!0;var s=e.dom,y=e.util,a=y.isHostMethod,c=e.DomRange,j=e.WrappedRange,J=e.DOMException,R=s.DomPosition,O,Q,K=e.features,H=s.getDocument,
r=s.getBody,W=c.rangesEqual,G=a(window,"getSelection"),A=y.isHostObject(document,"selection");K.implementsWinGetSelection=G;var t=(K.implementsDocSelection=A)&&(!G||e.config.preferTextRange);t?(O=I,e.isSelectionValid=function(a){var a=w(a,"isSelectionValid").document,b=a.selection;return"None"!=b.type||H(b.createRange().parentElement())==a}):G?(O=u,e.isSelectionValid=function(){return!0}):i.fail("Neither document.selection or window.getSelection() detected.");e.getNativeSelection=O;var G=O(),S=e.createNativeRange(document),
n=r(document),P=y.areHostProperties(G,["anchorNode","focusNode","anchorOffset","focusOffset"]);K.selectionHasAnchorAndFocus=P;var C=a(G,"extend");K.selectionHasExtend=C;var Z="number"==typeof G.rangeCount;K.selectionHasRangeCount=Z;var X=!1,ba=!0,U=C?function(a,b){var f=c.getRangeDocument(b),f=e.createRange(f);f.collapseToPoint(b.endContainer,b.endOffset);a.addRange(F(f));a.extend(b.startContainer,b.startOffset)}:null;y.areHostMethods(G,["addRange","getRangeAt","removeAllRanges"])&&("number"==typeof G.rangeCount&&
K.implementsDomRange)&&function(){var a=window.getSelection();if(a){for(var b=a.rangeCount,c=b>1,f=[],h=z(a),i=0;i<b;++i)f[i]=a.getRangeAt(i);var i=r(document),j=i.appendChild(document.createElement("div"));j.contentEditable="false";var k=j.appendChild(document.createTextNode("   ")),l=document.createRange();l.setStart(k,1);l.collapse(true);a.addRange(l);ba=a.rangeCount==1;a.removeAllRanges();if(!c){c=l.cloneRange();l.setStart(k,0);c.setEnd(k,3);c.setStart(k,2);a.addRange(l);a.addRange(c);X=a.rangeCount==
2;c.detach()}i.removeChild(j);a.removeAllRanges();for(i=0;i<b;++i)if(i==0&&h)if(U)U(a,f[i]);else{e.warn("Rangy initialization: original selection was backwards but selection has been restored forwards because the browser does not support Selection.extend");a.addRange(f[i])}else a.addRange(f[i])}}();K.selectionSupportsMultipleRanges=X;K.collapsedNonEditableSelectionsSupported=ba;var M=!1;n&&a(n,"createControlRange")&&(n=n.createControlRange(),y.areHostProperties(n,["item","add"])&&(M=!0));K.implementsControlRange=
M;Q=P?function(a){return a.anchorNode===a.focusNode&&a.anchorOffset===a.focusOffset}:function(a){return a.rangeCount?a.getRangeAt(a.rangeCount-1).collapsed:false};var $;a(G,"getRangeAt")?$=function(a,b){try{return a.getRangeAt(b)}catch(c){return null}}:P&&($=function(a){var b=H(a.anchorNode),b=e.createRange(b);b.setStartAndEnd(a.anchorNode,a.anchorOffset,a.focusNode,a.focusOffset);b.collapsed!==this.isCollapsed&&b.setStartAndEnd(a.focusNode,a.focusOffset,a.anchorNode,a.anchorOffset);return b});b.prototype=
e.selectionPrototype;var V=[],aa=function(a){if(a&&a instanceof b){a.refresh();return a}var a=w(a,"getNativeSelection"),c=f(a),e=O(a),h=A?I(a):null;if(c){c.nativeSelection=e;c.docSelection=h;c.refresh()}else{c=new b(e,h,a);V.push({win:a,selection:c})}return c};e.getSelection=aa;e.getIframeSelection=function(a){i.deprecationNotice("getIframeSelection()","getSelection(iframeEl)");return e.getSelection(s.getIframeWindow(a))};n=b.prototype;if(!t&&P&&y.areHostMethods(G,["removeAllRanges","addRange"]))n.removeAllRanges=
function(){this.nativeSelection.removeAllRanges();p(this)},n.addRange=Z?function(a,b){if(M&&A&&this.docSelection.type=="Control")B(this,a);else if(o(b)&&C){U(this.nativeSelection,a);this.refresh()}else{var c;if(X)c=this.rangeCount;else{this.removeAllRanges();c=0}this.nativeSelection.addRange(F(a).cloneRange());this.rangeCount=this.nativeSelection.rangeCount;if(this.rangeCount==c+1){if(e.config.checkSelectionRanges)(c=$(this.nativeSelection,this.rangeCount-1))&&!W(c,a)&&(a=new j(c));this._ranges[this.rangeCount-
1]=a;x(this,a,T(this.nativeSelection));this.isCollapsed=Q(this)}else this.refresh()}}:function(a,b){o(b)&&C?U(this.nativeSelection,a):this.nativeSelection.addRange(F(a));this.refresh()},n.setRanges=function(a){if(M&&a.length>1)l(this,a);else{this.removeAllRanges();for(var b=0,c=a.length;b<c;++b)this.addRange(a[b])}};else if(a(G,"empty")&&a(S,"select")&&M&&t)n.removeAllRanges=function(){try{this.docSelection.empty();if(this.docSelection.type!="None"){var a;if(this.anchorNode)a=H(this.anchorNode);else if(this.docSelection.type==
"Control"){var b=this.docSelection.createRange();b.length&&(a=H(b.item(0)))}if(a){r(a).createTextRange().select();this.docSelection.empty()}}}catch(c){}p(this)},n.addRange=function(a){if(this.docSelection.type=="Control")B(this,a);else{e.WrappedTextRange.rangeToTextRange(a).select();this._ranges[0]=a;this.rangeCount=1;this.isCollapsed=this._ranges[0].collapsed;x(this,a,false)}},n.setRanges=function(a){this.removeAllRanges();var b=a.length;b>1?l(this,a):b&&this.addRange(a[0])};else return i.fail("No means of selecting a Range or TextRange was found"),
!1;n.getRangeAt=function(a){if(a<0||a>=this.rangeCount)throw new J("INDEX_SIZE_ERR");return this._ranges[a].cloneRange()};var ca;if(t)ca=function(a){var b;if(e.isSelectionValid(a.win))b=a.docSelection.createRange();else{b=r(a.win.document).createTextRange();b.collapse(true)}a.docSelection.type=="Control"?E(a):b&&typeof b.text!="undefined"?L(a,b):p(a)};else if(a(G,"getRangeAt")&&"number"==typeof G.rangeCount)ca=function(a){if(M&&A&&a.docSelection.type=="Control")E(a);else{a._ranges.length=a.rangeCount=
a.nativeSelection.rangeCount;if(a.rangeCount){for(var b=0,c=a.rangeCount;b<c;++b)a._ranges[b]=new e.WrappedRange(a.nativeSelection.getRangeAt(b));x(a,a._ranges[a.rangeCount-1],T(a.nativeSelection));a.isCollapsed=Q(a)}else p(a)}};else if(P&&"boolean"==typeof G.isCollapsed&&"boolean"==typeof S.collapsed&&K.implementsDomRange)ca=function(a){var b;b=a.nativeSelection;if(b.anchorNode){b=$(b,0);a._ranges=[b];a.rangeCount=1;b=a.nativeSelection;a.anchorNode=b.anchorNode;a.anchorOffset=b.anchorOffset;a.focusNode=
b.focusNode;a.focusOffset=b.focusOffset;a.isCollapsed=Q(a)}else p(a)};else return i.fail("No means of obtaining a Range or TextRange from the user's selection was found"),!1;n.refresh=function(a){var b=a?this._ranges.slice(0):null,c=this.anchorNode,e=this.anchorOffset;ca(this);if(a){a=b.length;if(a!=this._ranges.length||this.anchorNode!=c||this.anchorOffset!=e)return true;for(;a--;)if(!W(b[a],this._ranges[a]))return true;return false}};var ea=function(a,b){var c=a.getAllRanges();a.removeAllRanges();
for(var e=0,f=c.length;e<f;++e)W(b,c[e])||a.addRange(c[e]);a.rangeCount||p(a)};n.removeRange=M?function(a){if(this.docSelection.type=="Control"){for(var b=this.docSelection.createRange(),a=D(a),c=H(b.item(0)),c=r(c).createControlRange(),e,f=false,h=0,i=b.length;h<i;++h){e=b.item(h);e!==a||f?c.add(b.item(h)):f=true}c.select();E(this)}else ea(this,a)}:function(a){ea(this,a)};var T;!t&&P&&K.implementsDomRange?(T=z,n.isBackward=function(){return T(this)}):T=n.isBackward=function(){return false};n.isBackwards=
n.isBackward;n.toString=function(){for(var a=[],b=0,c=this.rangeCount;b<c;++b)a[b]=""+this._ranges[b];return a.join("")};n.collapse=function(a,b){m(this,a);var c=e.createRange(a);c.collapseToPoint(a,b);this.setSingleRange(c);this.isCollapsed=true};n.collapseToStart=function(){if(this.rangeCount){var a=this._ranges[0];this.collapse(a.startContainer,a.startOffset)}else throw new J("INVALID_STATE_ERR");};n.collapseToEnd=function(){if(this.rangeCount){var a=this._ranges[this.rangeCount-1];this.collapse(a.endContainer,
a.endOffset)}else throw new J("INVALID_STATE_ERR");};n.selectAllChildren=function(a){m(this,a);var b=e.createRange(a);b.selectNodeContents(a);this.setSingleRange(b)};n.deleteFromDocument=function(){if(M&&A&&this.docSelection.type=="Control"){for(var a=this.docSelection.createRange(),b;a.length;){b=a.item(0);a.remove(b);b.parentNode.removeChild(b)}this.refresh()}else if(this.rangeCount){a=this.getAllRanges();if(a.length){this.removeAllRanges();b=0;for(var c=a.length;b<c;++b)a[b].deleteContents();this.addRange(a[c-
1])}}};n.eachRange=function(a,b){for(var c=0,e=this._ranges.length;c<e;++c)if(a(this.getRangeAt(c)))return b};n.getAllRanges=function(){var a=[];this.eachRange(function(b){a.push(b)});return a};n.setSingleRange=function(a,b){this.removeAllRanges();this.addRange(a,b)};n.callMethodOnEachRange=function(a,b){var c=[];this.eachRange(function(e){c.push(e[a].apply(e,b))});return c};n.setStart=k(!0);n.setEnd=k(!1);e.rangePrototype.select=function(a){aa(this.getDocument()).setSingleRange(this,a)};n.changeEachRange=
function(a){var b=[],c=this.isBackward();this.eachRange(function(c){a(c);b.push(c)});this.removeAllRanges();c&&b.length==1?this.addRange(b[0],"backward"):this.setRanges(b)};n.containsNode=function(a,b){return this.eachRange(function(c){return c.containsNode(a,b)},true)};n.getBookmark=function(a){return{backward:this.isBackward(),rangeBookmarks:this.callMethodOnEachRange("getBookmark",[a])}};n.moveToBookmark=function(a){for(var b=[],c=0,f,h;f=a.rangeBookmarks[c++];){h=e.createRange(this.win);h.moveToBookmark(f);
b.push(h)}a.backward?this.setSingleRange(b[0],"backward"):this.setRanges(b)};n.toHtml=function(){return this.callMethodOnEachRange("toHtml").join("")};n.getName=function(){return"WrappedSelection"};n.inspect=function(){return N(this)};n.detach=function(){f(this.win,"delete");h(this)};b.detachAll=function(){f(null,"deleteAll")};b.inspect=N;b.isDirectionBackward=o;e.Selection=b;e.selectionPrototype=n;e.addCreateMissingNativeApiListener(function(a){if(typeof a.getSelection=="undefined")a.getSelection=
function(){return aa(a)};a=null})});