volumes:
  redis-data: {}
  mysql-data: {}

services:
  web:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
      target: development
    environment:
      - APP_DOMAIN=localhost:12380
      - SITE_SUBDOMAIN=stdparteitag
      - DB_HOST=mysql
      - DB_NAME=antragsgruen
      - DB_USER=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - MAILER_DISABLED=true
      - MAIL_FROM_EMAIL=noreply@example.org
      - MAIL_FROM_NAME=Motion Tools
      - RANDOM_SEED=${RANDOM_SEED}
      - RABBITMQ_HOST=rabbitmq
      - WEASYPRINT_PATH=/usr/bin/weasyprint
      - IMAGE_MAGICK_PATH=/usr/bin/convert
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_SERVICE_NAME=antragsgruen
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otlp-collector:4318
      - OTEL_PROPAGATORS=baggage,tracecontext
      #- JWT_PRIVATE_KEY=/var/www/antragsgruen/config/jwt_private.key
      #- LIVE_INSTALLATION_ID=std
      #- LIVE_WS_URI=ws://localhost:8080/websocket
      #- LIVE_STOMP_JS_URI=http://localhost:8080/stomp.umd.min.js
      #- LIVE_RABBIT_MQ_URI=http://localhost:15672
      #- LIVE_RABBIT_MQ_EXCHANGE_NAME=antragsgruen-exchange
      #- LIVE_RABBIT_MQ_USERNAME=guest
      #- LIVE_RABBIT_MQ_PASSWORD=guest
    volumes:
      - "./:/var/www/antragsgruen"
      - "../antragsgruen-plugins/:/var/www/antragsgruen-plugins/:ro"

  live:
    build:
      context: ./docker/antragsgruen-live/
      dockerfile: ./docker/jdk/Dockerfile
      #target: build - enable this to use JDK image
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ANTRAGSGRUEN_INSTALLATIONS_0_ID=std
      - ANTRAGSGRUEN_WS_ORIGINS=http://localhost:12380
      - ANTRAGSGRUEN_INSTALLATIONS_0_PUBLIC_KEY=${ANTRAGSGRUEN_INSTALLATIONS_0_PUBLIC_KEY}
      - ACTUATOR_USER=admin
      - ACTUATOR_PASSWORD=${ACTUATOR_PASSWORD}
    env_file: .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 8080:8080
    profiles:
      - live

  nginx:
    image: nginx:latest
    ports:
      - "12380:80"
      - "12443:443"
    volumes:
      - "./:/var/www/antragsgruen:ro"
      - "./docker/nginx:/etc/nginx/conf.d"

  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - "mysql-data:/var/lib/mysql"

  redis:
    image: "redis:7"
    volumes:
      - 'redis-data:/data'

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    environment:
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_USER=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 3
    profiles:
      - live

  gulp-watch:
    image: 'node:22'
    volumes:
      - "./:/var/www/antragsgruen"
    working_dir: /var/www/antragsgruen
    command: "npx gulp watch"
    profiles:
      - gulp-watch

  node-helper:
    image: 'node:22'
    volumes:
      - "./:/var/www/antragsgruen"
    working_dir: /var/www/antragsgruen
    command: sleep infinity
    profiles:
      - node-helper

  otlp-collector:
    image: otel/opentelemetry-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
