<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '<?php echo $modelClass; ?>|<?php echo $this->pluralize($modelClass); ?>' => '',
  'Absatz' => '',
  'Abonnent|Abonnenten' => 'AbonnentIn|AbonnentInnen',
  'abonnenten' => 'AbonnentInnen',
  'Advanced Search' => 'Erweiterte Suche',
  'Aenderung Begruendung' => 'Änderung: Begründung',
  'Aenderung Text' => 'Änderung: Text',
  'AenderungsantragKommentar|AenderungsantragKommentare' => 'Änderungsantrag-Kommentar|Änderungsantrag-Kommentare',
  'AenderungsantragUnterstuetzerIn|AenderungsantragUnterstuetzerInnen' => 'Änderungantrags-UntertützerIn|Änderungantrags-UntertützerInnen',
  'Aenderungsantrag|Aenderungsantraege' => 'Änderungsantrag|Änderungsanträge',
  'All' => 'Alle',
  'Angelegt Datum' => '',
  'AntragKommentar|AntragKommentare' => 'Antragskommentar|Antragskommentare',
  'AntragUnterstuetzerIn|AntragUnterstuetzerInnen' => 'Antrags-UnterstützerIn|Antrags-UnterstützerInnen',
  'Antrag|Antraege' => 'Antrag|Anträge',
  'Auth' => '',
  'Begruendung' => 'Begründung',
  'Begruendung Neu' => 'Begründung (Neu)',
  'Create' => 'anlegen',
  'Datum' => '',
  'Datum Beschluss' => '',
  'Datum Bis' => '',
  'Datum Einreichung' => '',
  'Datum Von' => '',
  'Delete' => 'Löschen',
  'Email' => '',
  'Fields with' => 'Felder mit',
  'ID' => '',
  'Index' => '',
  'Kommentar' => '',
  'List' => 'Liste',
  'Manage' => 'verwalten',
  'Name' => '',
  'No' => 'Nein',
  'Person|people' => 'Person|Personen',
  'Revision Name' => '',
  'Rolle' => '',
  'Save' => 'Speichern',
  'Search' => 'Suche',
  'Status' => '',
  'Status String' => '',
  'Telefon' => '',
  'Text' => '',
  'Text Neu' => '',
  'Typ' => '',
  'Update' => 'Bearbeiten',
  'Veranstaltung|Veranstaltungen' => 'Veranstaltung|Veranstaltungen',
  'View' => 'Anzeigen',
  'Yes' => 'Ja',
  'Your request is invalid.' => '',
  'are required' => 'sind notwendig',
  'password' => '',
  '{$label}' => '',
);
