<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Array element type not supported (on key "{key}").' => '',
  'Array key type not supported.' => '',
  'Cannot save the related records to the database because the main record is new.' => '',
  'Composite primary keys are not supported.' => '',
  'Object serialization is not supported (on key "{key}").' => '',
  'Related model not found. Cannot continue without filling up the FK.' => '',
  'The argument "data" must be of type string or array.' => '',
  'The argument "relationName" must have a relation type of HAS_ONE, HAS_MANY or MANY_MANY.' => '',
  'The attribute "{attribute}" should be the last name.' => '',
  'The count of values in the argument "pk" ({countPk}) does not match the count of columns in the composite PK ({countColumns}).' => '',
  'The requested page does not exist.' => '',
  'This method should be overriden by the Active Record class.' => '',
  'Your request is invalid.' => '',
  'giix cannot handle automatically the POST data if "uncheckValue" is null.' => '',
);
