<?php

/**
 * This is the model base class for the table "aenderungsantrag".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Aenderungsantrag".
 *
 * Columns in table "aenderungsantrag" available as properties of the model,
 * followed by relations of table "aenderungsantrag" available as properties of the model.
 *
 * @property integer $id
 * @property integer $antrag_id
 * @property string $revision_name
 * @property string $name_neu
 * @property string $text_neu
 * @property string $begruendung_neu
 * @property string $aenderung_text
 * @property string $aenderung_begruendung
 * @property string $datum_einreichung
 * @property string $datum_beschluss
 * @property integer $status
 * @property string $status_string
 *
 * @property Antrag $antrag
 * @property AenderungsantragKommentar[] $aenderungsantragKommentare
 * @property AenderungsantragUnterstuetzer[] $aenderungsantragUnterstuetzer
 */
abstract class BaseAenderungsantrag extends IAntrag {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'aenderungsantrag';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Aenderungsantrag|Aenderungsantraege', $n);
	}

	public static function representingColumn() {
		return 'text_neu';
	}

	public function rules() {
		return array(
			array('text_neu, aenderung_text, datum_einreichung, status, status_string, status', 'required'),
			array('antrag_id, status', 'numerical', 'integerOnly'=>true),
			array('revision_name', 'length', 'max'=>45),
			array('status_string', 'length', 'max'=>55),
			array('name_neu, datum_beschluss', 'safe'),
			array('antrag_id, revision_name, name_neu, datum_beschluss', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, antrag_id, revision_name, name_neu, text_neu, begruendung_neu, aenderung_text, aenderung_begruendung, datum_einreichung, datum_beschluss, status, status_string', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'antrag' => array(self::BELONGS_TO, 'Antrag', 'antrag_id'),
			'aenderungsantragKommentare' => array(self::HAS_MANY, 'AenderungsantragKommentar', 'aenderungsantrag_id'),
			'aenderungsantragUnterstuetzer' => array(self::HAS_MANY, 'AenderungsantragUnterstuetzer', 'aenderungsantrag_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'antrag_id' => null,
			'revision_name' => Yii::t('app', 'Revision Name'),
			'name_neu' => Yii::t('app', 'Name Neu'),
			'text_neu' => Yii::t('app', 'Text Neu'),
			'begruendung_neu' => Yii::t('app', 'Begruendung Neu'),
			'aenderung_text' => Yii::t('app', 'Aenderung Text'),
			'aenderung_begruendung' => Yii::t('app', 'Aenderung Begruendung'),
			'datum_einreichung' => Yii::t('app', 'Datum Einreichung'),
			'datum_beschluss' => Yii::t('app', 'Datum Beschluss'),
			'status' => Yii::t('app', 'Status'),
			'status_string' => Yii::t('app', 'Status String'),
			'antrag' => null,
			'aenderungsantragKommentare' => null,
			'aenderungsantragUnterstuetzer' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('antrag_id', $this->antrag_id);
		$criteria->compare('revision_name', $this->revision_name, true);
		$criteria->compare('name_neu', $this->name_neu, true);
		$criteria->compare('text_neu', $this->text_neu, true);
		$criteria->compare('begruendung_neu', $this->begruendung_neu, true);
		$criteria->compare('aenderung_text', $this->aenderung_text, true);
		$criteria->compare('aenderung_begruendung', $this->aenderung_begruendung, true);
		$criteria->compare('datum_einreichung', $this->datum_einreichung, true);
		$criteria->compare('datum_beschluss', $this->datum_beschluss, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('status_string', $this->status_string, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}