<?php

/**
 * This is the model base class for the table "antrag_abo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AntragAbo".
 *
 * Columns in table "antrag_abo" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $antrag_id
 * @property integer $abonnent_id
 *
 */
abstract class BaseAntragAbo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'antrag_abo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AntragAbo|AntragAbos', $n);
	}

	public static function representingColumn() {
		return array(
			'antrag_id',
			'abonnent_id',
		);
	}

	public function rules() {
		return array(
			array('antrag_id, abonnent_id', 'required'),
			array('antrag_id, abonnent_id', 'numerical', 'integerOnly'=>true),
			array('antrag_id, abonnent_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'antrag_id' => null,
			'abonnent_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('antrag_id', $this->antrag_id);
		$criteria->compare('abonnent_id', $this->abonnent_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}