<?php

/**
 * This is the model base class for the table "aenderungsantrag_kommentar".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AenderungsantragKommentar".
 *
 * Columns in table "aenderungsantrag_kommentar" available as properties of the model,
 * followed by relations of table "aenderungsantrag_kommentar" available as properties of the model.
 *
 * @property integer $id
 * @property integer $verfasser_id
 * @property integer $aenderungsantrag_id
 * @property integer $absatz
 * @property string $text
 * @property string $datum
 * @property integer $status
 *
 * @property Aenderungsantrag $aenderungsantrag
 * @property Person $verfasser
 */
abstract class BaseAenderungsantragKommentar extends IKommentar {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'aenderungsantrag_kommentar';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AenderungsantragKommentar|AenderungsantragKommentare', $n);
	}

	public static function representingColumn() {
		return 'datum';
	}

	public function rules() {
		return array(
			array('datum', 'required'),
			array('verfasser_id, aenderungsantrag_id, absatz, status', 'numerical', 'integerOnly'=>true),
			array('text', 'length', 'max'=>45),
			array('verfasser_id, aenderungsantrag_id, absatz, text, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, verfasser_id, aenderungsantrag_id, absatz, text, datum, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'aenderungsantrag' => array(self::BELONGS_TO, 'Aenderungsantrag', 'aenderungsantrag_id'),
			'verfasser' => array(self::BELONGS_TO, 'Person', 'verfasser_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'verfasser_id' => null,
			'aenderungsantrag_id' => null,
			'absatz' => Yii::t('app', 'Absatz'),
			'text' => Yii::t('app', 'Text'),
			'datum' => Yii::t('app', 'Datum'),
			'status' => Yii::t('app', 'Status'),
			'aenderungsantrag' => null,
			'verfasser' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('verfasser_id', $this->verfasser_id);
		$criteria->compare('aenderungsantrag_id', $this->aenderungsantrag_id);
		$criteria->compare('absatz', $this->absatz);
		$criteria->compare('text', $this->text, true);
		$criteria->compare('datum', $this->datum, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}