DELETE FROM cl USING consultationLog cl JOIN consultation c ON cl.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM mt USING motionTag mt JOIN motion m ON mt.motionId = m.id JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM amt USING amendmentTag amt JOIN amendment a ON amt.amendmentId = a.id JOIN motion m ON a.motionId = m.id JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM mc USING motionComment mc JOIN motion m ON mc.motionId = m.id JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM amc USING amendmentComment amc JOIN amendment a ON amc.amendmentId = a.id JOIN motion m ON a.motionId = m.id JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM mc USING motionAdminComment mc JOIN motion m ON mc.motionId = m.id JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM amc USING amendmentAdminComment amc JOIN amendment a ON amc.amendmentId = a.id JOIN motion m ON a.motionId = m.id JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM cfg USING consultationFileGroup cfg JOIN consultation c ON cfg.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM cf USING consultationFile cf JOIN consultation c ON cf.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM cf USING consultationFile cf JOIN site s ON cf.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM ms USING motionSupporter ms JOIN motion m ON ms.motionId = m.id JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM ams USING amendmentSupporter ams JOIN amendment a ON ams.amendmentId = a.id JOIN motion m ON a.motionId = m.id JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM ams USING amendmentSection ams JOIN amendment a ON ams.amendmentId = a.id JOIN motion m ON a.motionId = m.id JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM ms USING motionSection ms JOIN motion m ON ms.motionId = m.id JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
UPDATE motion m JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id SET m.parentMotionId = NULL WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM v USING vote v JOIN votingBlock vb ON v.votingBlockId = vb.id JOIN consultation c ON vb.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
UPDATE motion m JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id SET m.votingBlockId = NULL WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
UPDATE amendment a JOIN motion m ON a.motionId = m.id JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id SET a.votingBlockId = NULL WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM a USING amendment a JOIN motion m ON a.motionId = m.id JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM vq USING votingQuestion vq JOIN consultation c ON vq.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM vb USING votingBlock vb JOIN consultation c ON vb.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM m USING motion m JOIN consultation c ON m.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM el USING emailLog el JOIN site s ON el.fromSiteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM sqi USING speechQueueItem sqi JOIN speechQueue sq ON sqi.queueId = sq.id JOIN consultation c ON sq.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM ssq USING speechSubqueue ssq JOIN speechQueue sq ON ssq.queueId = sq.id JOIN consultation c ON sq.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM sq USING speechQueue sq JOIN consultation c ON sq.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM cai USING consultationAgendaItem cai JOIN consultation c ON cai.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM csm USING consultationSettingsMotionSection csm JOIN consultationMotionType cmt ON csm.motionTypeId = cmt.id JOIN consultation c ON cmt.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM cmt USING consultationMotionType cmt JOIN consultation c ON cmt.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM ct USING consultationSettingsTag ct JOIN consultation c ON ct.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM ct USING consultationText ct JOIN consultation c ON ct.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM ug USING userGroup ug JOIN consultationUserGroup cug ON ug.groupId = cug.id JOIN consultation c ON cug.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM cug USING consultationUserGroup cug JOIN consultation c ON cug.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM un USING userNotification un JOIN consultation c ON un.consultationId = c.id JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
UPDATE site SET site.currentConsultationId = NULL WHERE site.subdomain IS NULL AND site.dateDeletion IS NOT NULL;
DELETE FROM c USING consultation c JOIN site s ON c.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM ug USING userGroup ug JOIN consultationUserGroup cug ON ug.groupId = cug.id JOIN site s ON cug.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM cug USING consultationUserGroup cug JOIN site s ON cug.siteId = s.id WHERE s.subdomain IS NULL AND s.dateDeletion IS NOT NULL;
DELETE FROM site WHERE subdomain IS NULL AND dateDeletion IS NOT NULL;
