SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

INSERT INTO `texTemplate` (`id`, `siteId`, `title`, `texLayout`, `texContent`) VALUES
  (1, NULL, 'Standard (Grünes CI)',
   '\\documentclass[paper=a4, 12pt, pagesize, parskip=half, DIV=calc]{scrartcl}\n\\usepackage[T1]{fontenc}\n\\usepackage{lmodern}\n\\usepackage[%LANGUAGE%]{babel}\n\\usepackage{fixltx2e}\n\\usepackage{lineno}\n\\usepackage{tabularx}\n\\usepackage{scrpage2}\n\\usepackage[normalem]{ulem}\n\\usepackage[right]{eurosym}\n\\usepackage{fontspec}\n\\usepackage{geometry}\n\\usepackage{color}\n\\usepackage{lastpage}\n\\usepackage[normalem]{ulem}\n\\usepackage{hyperref}\n\n\\newfontfamily\\ArvoGruen[\n  Path=%ASSETROOT%Arvo/\n]{Arvo_Gruen_1004.otf}\n\\newfontfamily\\ArvoRegular[\n  Path=%ASSETROOT%Arvo/\n]{Arvo-Regular_v104.ttf}\n\\newfontfamily\\AntragsgruenSection[\n  Path=%ASSETROOT%Arvo/\n]{Arvo-Regular_v104.ttf}\n\\setmainfont[\n  Path=%ASSETROOT%PT-Sans/,\n  BoldFont=PTS75F.ttf,\n  ItalicFont=PTS56F.ttf,\n  BoldItalicFont=PTS76F.ttf\n]{PTS55F.ttf}\n\n\\definecolor{Insert}{rgb}{0,1,0}\n\\definecolor{Delete}{rgb}{1,0,0}\n\n\\hypersetup{\n    colorlinks=true,\n    linkcolor=blue,\n    filecolor=blue,      \n    urlcolor=blue,\n} \n\\urlstyle{same}\n\n\\title{%TITLE%}\n\\author{%AUTHOR%}\n\\geometry{a4paper, portrait, top=10mm, left=20mm, right=15mm, bottom=25mm, includehead=true}\n\n\\pagestyle{scrheadings}\n\\clearscrheadfoot\n\\ohead{\\ArvoRegular \\footnotesize %TITLE%}\n\\ifoot{\\ArvoRegular \\footnotesize Seite \\thepage\\ / \\pageref{LastPage}}\n\\setheadsepline{0.4pt}\n\\setfootsepline{0.4pt}\n\n\\begin{document}\n\n\\shorthandoff{"}\n\\sloppy\n\\hyphenpenalty=10000\n\\hbadness=10000\n\n%CONTENT%\n\n\\end{document}',
   '\\thispagestyle{empty}\r\n\r\n\\vspace*{-25mm}\r\n\\begin{flushright}\r\n \\ArvoRegular\r\n \\small\r\n \\textbf{\\normalsize %INTRODUCTION_BIG%}\\\\\r\n %INTRODUCTION_SMALL%\r\n\\end{flushright}\r\n\r\n\\begin{tabularx}{\\textwidth}{|lX|}\r\n    \\cline{1-2}\r\n    \\ArvoGruen\r\n&                               \\\\\r\n    \\multicolumn{2}{|l|}{\r\n    \\parbox{17cm}{\\raggedright\\textbf{\\LARGE %TITLEPREFIX%} %TITLE%      }} \\\\\r\n                                                            &                               \\\\\r\n    %MOTION_DATA_TABLE%\r\n                                                            &                               \\\\\r\n    \\cline{1-2}\r\n\\end{tabularx}\r\n\r\n\\section*{\\ArvoRegular %TITLE_LONG%}\r\n\\raggedright\r\n\r\n%TEXT%\r\n');

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
