<?php

namespace app\models\db;

use app\components\LanguageTools;
use app\models\exceptions\Internal;
use app\models\sectionTypes\{Choice, Image, ISectionType, TabularData, TextEditorial, TextHTML, TextSimple, Title, PDF, VideoEmbed};
use app\models\settings\AntragsgruenApp;
use yii\db\ActiveRecord;

/**
 * @property string $data
 * @property string|null $dataRaw
 * @property int $public
 * @property int $sectionId
 * @property string|null $metadata
 */
abstract class IMotionSection extends ActiveRecord
{
    abstract public function getSettings(): ?ConsultationSettingsMotionSection;

    /**
     * @throws Internal
     */
    public function getSectionType(): ISectionType
    {
        return match ($this->getSettings()->type) {
            ISectionType::TYPE_TITLE => new Title($this),
            ISectionType::TYPE_TEXT_HTML => new TextHTML($this),
            ISectionType::TYPE_TEXT_SIMPLE => new TextSimple($this),
            ISectionType::TYPE_TEXT_EDITORIAL => new TextEditorial($this),
            ISectionType::TYPE_IMAGE => new Image($this),
            ISectionType::TYPE_TABULAR => new TabularData($this),
            ISectionType::TYPE_CHOICE => new Choice($this),
            ISectionType::TYPE_PDF_ATTACHMENT, ISectionType::TYPE_PDF_ALTERNATIVE => new PDF($this),
            ISectionType::TYPE_VIDEO_EMBED => new VideoEmbed($this),
            default => throw new Internal('Unknown Field Type: ' . $this->getSettings()->type),
        };
    }

    public function checkLength(): bool
    {
        // @TODO
        return true;
    }

    abstract public function getFirstLineNumber(): int;

    public function isLayoutRight(): bool
    {
        return ($this->getSettings()->positionRight == 1);
    }

    public function getShowAlwaysToken(): string
    {
        return sha1('createToken' . AntragsgruenApp::getInstance()->randomSeed . $this->getData());
    }

    abstract public function getData(): string;

    abstract public function setData(string $data): void;

    /**
     * The language this section is specific to, or null if it applies regardless of language.
     */
    public function getDisplayLanguage(): ?string
    {
        return $this->getSettings()?->getLanguage();
    }

    /**
     * Whether this section's language differs from the reader's (D12): only then does a view need
     * to show a language label / "not available in your language" disclaimer. A section without a
     * language (valid for every language) never needs one.
     */
    public function needsLanguageLabel(?string $readerLanguage = null): bool
    {
        $language = $this->getDisplayLanguage();
        if ($language === null) {
            return false;
        }

        $readerLanguage ??= LanguageTools::getCurrentLanguage();

        return $language !== $readerLanguage;
    }

    /**
     * Whether this section has anything meaningful to show, for MotionSectionLanguageFilter's
     * D4 fallback decision (prefer a language with content over an empty one in the reader's own
     * language). Plain "not empty" for a motion section. AmendmentSection overrides this: an
     * amendment section is always pre-filled with the motion's original text, even where the
     * amendment doesn't touch it, so "not empty" alone would treat every language as having content.
     */
    public function hasContentForFiltering(): bool
    {
        return !$this->getSectionType()->isEmpty();
    }

    private const METADATA_AUTOFILL_KEY = 'autofill';

    /**
     * @return array<string, mixed>
     */
    private function getMetadataArray(): array
    {
        $decoded = ($this->metadata ? json_decode($this->metadata, true) : null);
        return is_array($decoded) ? $decoded : [];
    }

    /**
     * Marks this section's current content as having been generated by a plugin (see
     * components/SectionAutofill.php) rather than typed in by a human. Stored the same way Image
     * sections store width/height/filesize/mime here (models/sectionTypes/Image.php) - free-form
     * per-section JSON, just under a key that isn't specific to any one section type.
     */
    public function markAsAutofilled(string $pluginId): void
    {
        $metadata = $this->getMetadataArray();
        $metadata[self::METADATA_AUTOFILL_KEY] = ['plugin' => $pluginId];
        $this->metadata = json_encode($metadata, JSON_THROW_ON_ERROR);
    }

    /**
     * The plugin ID that generated this section's current content via SectionAutofill, or null if it
     * wasn't (or is no longer, see clearAutofillMarker()).
     */
    public function getAutofillPluginId(): ?string
    {
        $plugin = $this->getMetadataArray()[self::METADATA_AUTOFILL_KEY]['plugin'] ?? null;
        return is_string($plugin) ? $plugin : null;
    }

    /**
     * Called by setData() implementations before applying new content, so a section a plugin
     * previously auto-filled stops being marked as such the moment a human (or anything else) writes
     * over it - without this, the marker set by markAsAutofilled() would silently go stale and
     * mislabel human-written content as machine-generated.
     */
    protected function clearAutofillMarker(): void
    {
        $metadata = $this->getMetadataArray();
        if (isset($metadata[self::METADATA_AUTOFILL_KEY])) {
            unset($metadata[self::METADATA_AUTOFILL_KEY]);
            $this->metadata = ($metadata ? json_encode($metadata, JSON_THROW_ON_ERROR) : null);
        }
    }
}
