//! Longest common subsequence diff, used by app\components\diff\Engine::compareArrays().
//!
//! The result has to be identical to the PHP implementation (Engine::computeTable() and
//! Engine::generatePartialDiff()), including the choices made between equally long subsequences.
//! Otherwise, a diff would look differently depending on whether the extension is loaded.

pub const UNMODIFIED: i64 = 0;
pub const DELETED: i64 = 1;
pub const INSERTED: i64 = 2;

/// Takes two sequences of comparison IDs (two tokens are considered equal if they have the same ID)
/// and returns the operations transforming the first sequence into the second, in forward order.
pub fn lcs_ops(seq1: &[i64], seq2: &[i64]) -> Vec<i64> {
    let (len1, len2) = (seq1.len(), seq2.len());
    let width = len2 + 1;

    // Table of longest common subsequence lengths; row 0 and column 0 stay 0
    let mut table = vec![0u32; (len1 + 1) * width];
    for index1 in 1..=len1 {
        let id1 = seq1[index1 - 1];
        let (prev_row, row) = table[(index1 - 1) * width..(index1 + 1) * width].split_at_mut(width);
        let mut left = 0u32;
        for index2 in 1..=len2 {
            left = if id1 == seq2[index2 - 1] {
                prev_row[index2 - 1] + 1
            } else if prev_row[index2] > left {
                prev_row[index2]
            } else {
                left
            };
            row[index2] = left;
        }
    }

    // Walking back from the end; same order of checks as Engine::generatePartialDiff()
    let (mut index1, mut index2) = (len1, len2);
    let mut ops = Vec::with_capacity(len1 + len2);
    while index1 > 0 || index2 > 0 {
        if index1 > 0 && index2 > 0 && seq1[index1 - 1] == seq2[index2 - 1] {
            ops.push(UNMODIFIED);
            index1 -= 1;
            index2 -= 1;
        } else if index2 > 0 && table[index1 * width + index2] == table[index1 * width + index2 - 1] {
            ops.push(INSERTED);
            index2 -= 1;
        } else {
            ops.push(DELETED);
            index1 -= 1;
        }
    }
    ops.reverse();
    ops
}

#[cfg(test)]
mod tests {
    use super::*;

    const U: i64 = UNMODIFIED;
    const D: i64 = DELETED;
    const I: i64 = INSERTED;

    #[test]
    fn empty_sequences() {
        assert_eq!(lcs_ops(&[], &[]), Vec::<i64>::new());
        assert_eq!(lcs_ops(&[1, 2], &[]), vec![D, D]);
        assert_eq!(lcs_ops(&[], &[1, 2]), vec![I, I]);
    }

    #[test]
    fn identical() {
        assert_eq!(lcs_ops(&[1, 2, 3], &[1, 2, 3]), vec![U, U, U]);
    }

    #[test]
    fn replace_and_insert() {
        assert_eq!(lcs_ops(&[1, 2, 3, 4], &[1, 3, 5, 4]), vec![U, D, U, I, U]);
    }

    #[test]
    fn replacement_lists_deletion_before_insertion() {
        // Engine::compareArrays() relies on DELETED being emitted before INSERTED for a replaced token
        assert_eq!(lcs_ops(&[1, 2, 3], &[1, 4, 3]), vec![U, D, I, U]);
    }

    #[test]
    fn ambiguous_alignment_matches_php() {
        // Expected values generated by Engine::computeTable() / generatePartialDiff()
        assert_eq!(lcs_ops(&[1, 2, 1, 2], &[2, 1, 2, 1]), vec![D, U, U, U, I]);
        assert_eq!(lcs_ops(&[1, 1, 2], &[1, 2, 2]), vec![D, U, I, U]);
        assert_eq!(lcs_ops(&[1, 2, 3], &[3, 2, 1]), vec![D, D, U, I, I]);
        assert_eq!(lcs_ops(&[5, 6, 5], &[6, 5, 6, 5]), vec![I, U, U, U]);
    }
}
