SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP TABLE IF EXISTS `site`;
DROP TABLE IF EXISTS `consultation`;
DROP TABLE IF EXISTS `motion`;
DROP TABLE IF EXISTS `amendment`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `amendment_comment`;
DROP TABLE IF EXISTS `amendment_supporter`;
DROP TABLE IF EXISTS `motion_subscription`;
DROP TABLE IF EXISTS `motion_comment`;
DROP TABLE IF EXISTS `motion_comment_supporter`;
DROP TABLE IF EXISTS `motion_supporter`;
DROP TABLE IF EXISTS `cache`;
DROP TABLE IF EXISTS `consultation_text`;
DROP TABLE IF EXISTS `consultation_admin`;
DROP TABLE IF EXISTS `consultation_subscription`;
DROP TABLE IF EXISTS `site_admin`;
DROP TABLE IF EXISTS `email_log`;
DROP TABLE IF EXISTS `consultation_odt_template`;
DROP TABLE IF EXISTS `consultation_tag`;
DROP TABLE IF EXISTS `motion_tag`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
