[node]
drivers = ["chrome"]
detect-drivers = false
[[node.driver-configuration]]
display-name = "Chrome 117"
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"117\", \"platformName\": \"MAC\", \"goog:chromeOptions\": {\"binary\": \"./chrome-117/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing\"}}"
webdriver-executable = './chrome-117/chromedriver-mac-arm64/chromedriver'

