<?php

declare(strict_types=1);

namespace Tests\Unit;

use app\models\db\AmendmentSection;
use Codeception\Attribute\Group;
use Tests\Support\Helper\DBTestBase;

/**
 * Covers the generic autofill-metadata marker on IMotionSection (markAsAutofilled()/
 * getAutofillPluginId(), plus clearAutofillMarker() via setData()) - the mechanism
 * components/SectionAutofill.php uses to record that a section's content was generated by a plugin,
 * the same way models/sectionTypes/Image.php stores width/height/filesize/mime in $section->metadata.
 * Uses AmendmentSection because its setData() has no further DB dependency of its own (unlike
 * MotionSection's, which also calls getSettings() - covered by SectionAutofillTest instead); DB-backed
 * regardless, since even reading a plain property like ->metadata on an ActiveRecord object requires
 * a schema lookup.
 */
#[Group('database')]
class IMotionSectionAutofillMarkerTest extends DBTestBase
{
    public function testANewSectionHasNoAutofillMarker(): void
    {
        $section = new AmendmentSection();
        $this->assertNull($section->getAutofillPluginId());
    }

    public function testMarkAsAutofilledRoundTrips(): void
    {
        $section = new AmendmentSection();
        $section->markAsAutofilled('translation_claude');

        $this->assertSame('translation_claude', $section->getAutofillPluginId());
    }

    public function testMarkingPreservesOtherMetadataKeys(): void
    {
        $section = new AmendmentSection();
        $section->metadata = json_encode(['width' => 42], JSON_THROW_ON_ERROR);

        $section->markAsAutofilled('translation_claude');

        $metadata = json_decode((string) $section->metadata, true);
        $this->assertSame(42, $metadata['width']);
        $this->assertSame('translation_claude', $section->getAutofillPluginId());
    }

    public function testSettingNewDataClearsAStaleAutofillMarker(): void
    {
        $section = new AmendmentSection();
        $section->markAsAutofilled('translation_claude');

        // A human (or anything else) overwriting the content must not leave the section mislabelled
        // as machine-generated.
        $section->setData('Written by a human');

        $this->assertNull($section->getAutofillPluginId());
    }

    public function testSettingTheSameDataPreservesTheAutofillMarker(): void
    {
        $section = new AmendmentSection();
        $section->setData('Generated text');
        $section->markAsAutofilled('translation_claude');

        // Admin forms resubmit every section's current value on every save, whether or not the admin
        // actually touched it - re-setting the identical value must not be mistaken for an edit.
        $section->setData('Generated text');

        $this->assertSame('translation_claude', $section->getAutofillPluginId());
    }
}
