name: phpstan-generate-baseline

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-baseline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: zip, intl, gd
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction
      - name: Install extra packages
        run: composer require --no-interaction yiisoft/yii2-redis predis/predis simplesamlphp/simplesamlphp
      - name: Generate baseline
        run: |
          php vendor/bin/phpstan analyse --configuration=phpstan.neon --error-format=github --generate-baseline
      - name: Upload baseline
        uses: actions/upload-artifact@v7
        with:
          name: phpstan-baseline.neon
          path: phpstan-baseline.neon
