name: phpstan-evaluate-pr

on:
  pull_request: {}

jobs:
  evaluate-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          php_version: "8.0"
          php_extensions: zip intl gd
      - uses: php-actions/composer@v6
        with:
          php_version: "8.0"
          php_extensions: zip intl gd
          command: require yiisoft/yii2-redis predis/predis simplesamlphp/simplesamlphp
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: .github/workflows/phpstan-generate-baseline.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.base.sha}}
          name: phpstan-baseline.neon
      - name: phpstan
        run: |
          php vendor/bin/phpstan analyse --configuration=phpstan.use-baseline.neon --error-format=github
