name: phpstan-evaluate-pr

on:
  pull_request: {}

permissions:
  contents: read   # ← Add this block

jobs:
  evaluate-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: zip, intl, gd
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction
      - name: Install extra packages
        run: composer require --no-interaction yiisoft/yii2-redis predis/predis simplesamlphp/simplesamlphp
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v21
        with:
          workflow: .github/workflows/phpstan-generate-baseline.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.base.sha}}
          name: phpstan-baseline.neon
      - name: phpstan
        run: |
          php vendor/bin/phpstan analyse --configuration=phpstan.use-baseline.neon --error-format=github
