name: phpstan-evaluate-pr

on:
  pull_request: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  evaluate-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: zip, intl, gd
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction
      - name: Install PHPStan extras
        run: composer install --prefer-dist --no-progress --no-interaction --working-dir=.github/phpstan
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v21
        with:
          workflow: .github/workflows/phpstan-generate-baseline.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.base.sha}}
          name: phpstan-baseline.neon
      - name: phpstan
        run: |
          php vendor/bin/phpstan analyse --configuration=phpstan.use-baseline.neon --error-format=github
